force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sales_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>Greater China</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>SEAP</fullName>
        <isActive>false</isActive>
        <label>SEAP</label>
    </customValue>
    <description>(BGI) Ingredients Sales Regions</description>
    <masterLabel>Sales Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProcessInstanceWorkitemControllerTest.cls
@isTest
public class ProcessInstanceWorkitemControllerTest {

    @isTest
    static void testGetProcessInstanceWorkitem() {
		Account commercialCustIMCD = TestUtility.createAccount('IMCD Holding');
        Insert commercialCustIMCD;
        
        RecordType recordType = [SELECT Id,Name,DeveloperName FROM RecordType WHERE DeveloperName ='FCI_TSS_Case']; 
        Case testCase = new Case(
            Subject = 'Test Case',
            Description = 'Test Description',
            Type = 'Customer/Sales Support',
            Sub_Type__c = 'Application Project',
            Region__c = 'APAC',
            AccountId = commercialCustIMCD.Id,
            RecordTypeId = recordType.Id
        );
        insert testCase;

        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(testCase.Id);
        Approval.ProcessResult result = Approval.process(req);
        System.assert(result.isSuccess());
        List<Id> newWorkitemIds = result.getNewWorkitemIds();
        String targetObjectId = ProcessInstanceWorkitemController.getProcessInstanceWorkitem(newWorkitemIds[0]);
        System.assertEquals(testCase.Id, targetObjectId);
    }
}